### PR TITLE
Add support for other default color themes

### PR DESCRIPTION
**Pull request by maciejpedzich**
This pull request adds support for all the other default color themes, i.e.
 - Quiet Light
 - Solarized Night
 - Abyss
 - Dark
 - Dark +
 - Kimbie Dark
 - Monokai
 - Monokai Dimmed
 - Red
 - Solarized Dark
 - Tomorrow Night Blue
 - High Contrast

All of them should work properly with Teditor.

### CODE REVIEW

**Comment by TobiasNickel** [comment]
I like it, will try it this evening before merging.

**Comment by maciejpedzich** [comment]
> I like it, will try it this evening before merging.

Thanks! All themes were directly "ported" from VSCode's repository, so they should work just fine.

**Comment by TobiasNickel** [comment]
ok, to change them we have to use, F1 then type 'theme',... I think before it was in the view menue. but even my local vscode does not have it there anymore. 

I will deploy it at the weekend, when I do some more updates.

Thanks

**Comment by maciejpedzich** [comment]
> ok, to change them we have to use, F1 then type 'theme',... I think before it was in the view menue. but even my local vscode does not have it there anymore.
> 
> I will deploy it at the weekend, when I do some more updates.
> 
> Thanks

No problem, glad to contribute to this project. I'm really looking forward to seeing it grow.

**Pull request merged**
